### ISSUE TITLE
Please use the AGLP v3 instead, it's such a lovely license.

### ISSUE THREAD

**Issue by leogallego** [fepe55/whoheplayfor#1]
As your software is a server side application, and therefore is intended to run over a network, using the AGPL would allow anyone to use it and modify it, while at the same time, allow the modifications to remain free. The AGPL was specifically created for the purpose of allowing server side (usually referred as SaaS) applications and their modifications to the source code to remain freely available.

The article that applies to this condition is the 13th:

> 13. Remote Network Interaction; Use with the GNU General Public License.
> 
>   Notwithstanding any other provision of this License, if you modify the
> Program, your modified version must prominently offer all users
> interacting with it remotely through a computer network (if your version
> supports such interaction) an opportunity to receive the Corresponding
> Source of your version by providing access to the Corresponding Source
> from a network server at no charge, through some standard or customary
> means of facilitating copying of software.  This Corresponding Source
> shall include the Corresponding Source for any work covered by version 3
> of the GNU General Public License that is incorporated pursuant to the
> following paragraph.
> 
>   Notwithstanding any other provision of this License, you have
> permission to link or combine any covered work with a work licensed
> under version 3 of the GNU General Public License into a single
> combined work, and to convey the resulting work.  The terms of this
> License will continue to apply to the part which is the covered work,
> but the work with which it is combined will remain governed by version
> 3 of the GNU General Public License.
> 

More information:
https://www.gnu.org/licenses/why-affero-gpl.en.html

A nice article about it (and MongoDB use case):
https://www.synopsys.com/blogs/software-security/agpl-affero-gpl-3/

The license:
https://www.gnu.org/licenses/agpl.txt

**Comment by fepe55** [comment]
Done!

Thanks
