### ISSUE TITLE
Update team logo sources

### ISSUE THREAD

**Issue by aiden-gonzalez** [fepe55/whoheplayfor#7]
Seems that the team logos have become unavailable.  Suggest replacing them with new links to correctly load team logos once again!
![image](https://user-images.githubusercontent.com/30540732/201375013-33cbecc6-62ad-4f68-914d-9caa6727d497.png)

Examples:
https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/ORL.svg
https://i.cdn.turner.com/nba/nba/assets/logos/teams/primary/web/MEM.svg

**Comment by fepe55** [comment]
Thanks man! Just fixed it. The new NBA logos are not the most friendly for my current background, but at least we can see logos
